### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by m121** [sayyam/instagramapi#1]
compile 'com.github.sayyam:instagramapi:0.0.4'

Sorry I am a beginner developer, but I can't compile this, what it's wrong?

**Comment by tunjid** [comment]
@m121 The library is hosted on a different maven repo. Add this to the respositories block under your top level build.gradle:  
`maven { url 'https://dl.bintray.com/sayyam/maven' }
`

The full thing should look something like this:

```
buildscript {
repositories {
jcenter()
maven { url 'https://dl.bintray.com/sayyam/maven' }
}
dependencies {
classpath 'com.android.tools.build:gradle:2.0.0'
}
}

allprojects {
repositories {
jcenter()
maven { url 'https://dl.bintray.com/sayyam/maven' }
}
}
```

**Comment by m121** [comment]
Thank you
